create table public.categories (
  id integer generated by default as identity primary key,
  name text not null unique
);

insert into public.categories (id, name)
values
  (1, 'painting'),
  (2, 'drawing'),
  (3, 'woodworking'),
  (4, 'other');

select setval(
  pg_get_serial_sequence('public.categories', 'id'),
  (select max(id) from public.categories),
  true
);

create table public.artwork (
  id bigint generated by default as identity primary key,
  title text not null,
  date date not null,
  description text not null,
  images jsonb not null default '[]'::jsonb,
  gallery_image text,
  constraint artwork_images_must_be_array check (jsonb_typeof(images) = 'array')
);

create table public.artwork_categories (
  artwork_id bigint not null references public.artwork(id)
    on update cascade on delete cascade,
  category_id integer not null references public.categories(id)
    on update cascade on delete restrict,
  primary key (artwork_id, category_id)
);

alter table public.categories enable row level security;
alter table public.artwork enable row level security;
alter table public.artwork_categories enable row level security;

create policy "Anyone can view categories"
  on public.categories
  for select
  to anon, authenticated
  using (true);

create policy "Authenticated users can create categories"
  on public.categories
  for insert
  to authenticated
  with check (true);

create policy "Authenticated users can update categories"
  on public.categories
  for update
  to authenticated
  using (true)
  with check (true);

create policy "Authenticated users can delete categories"
  on public.categories
  for delete
  to authenticated
  using (true);

create policy "Anyone can view artwork"
  on public.artwork
  for select
  to anon, authenticated
  using (true);

create policy "Authenticated users can create artwork"
  on public.artwork
  for insert
  to authenticated
  with check (true);

create policy "Authenticated users can update artwork"
  on public.artwork
  for update
  to authenticated
  using (true)
  with check (true);

create policy "Authenticated users can delete artwork"
  on public.artwork
  for delete
  to authenticated
  using (true);

create policy "Anyone can view artwork categories"
  on public.artwork_categories
  for select
  to anon, authenticated
  using (true);

create policy "Authenticated users can assign artwork categories"
  on public.artwork_categories
  for insert
  to authenticated
  with check (true);

create policy "Authenticated users can change artwork categories"
  on public.artwork_categories
  for update
  to authenticated
  using (true)
  with check (true);

create policy "Authenticated users can remove artwork categories"
  on public.artwork_categories
  for delete
  to authenticated
  using (true);

grant select on table public.categories, public.artwork, public.artwork_categories
  to anon, authenticated;
grant insert, update, delete on table public.categories, public.artwork, public.artwork_categories
  to authenticated;
grant usage, select on sequence public.artwork_id_seq to authenticated;