alter table public.categories
  alter column id add generated by default as identity;

select setval(
  pg_get_serial_sequence('public.categories', 'id'),
  greatest(coalesce((select max(id) from public.categories), 0), 1),
  true
);
